In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('gurgaon_properties_missing_value_imputation.csv')

In [4]:
df.shape

(3556, 24)

In [5]:
df.head()

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,floorNum,facing,agePossession,super_built_up_area,built_up_area,carpet_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score,area_room_ratio
0,flat,mapsko mount ville,sector 79,1.10,12731.0,864.0,Super Built up area 1490(138.43 sq.m.)Carpet a...,3,3,3,22.0,South-West,Relatively New,1490.0,NaN,863.91,1,0,0,1,0,0,135,288.000000
1,flat,ansal estella,sector 103,1.50,8671.0,1730.0,Super Built up area 1730(160.72 sq.m.)Carpet a...,3,3,3+,6.0,NaN,Under Construction,1730.0,NaN,1725.00,0,0,0,0,0,0,58,576.666667
2,flat,chd avenue,sector 71,0.95,7930.0,1198.0,Super Built up area 1198(111.3 sq.m.),2,2,2,5.0,South,Moderately Old,1198.0,NaN,NaN,0,0,0,0,0,1,142,599.000000
3,flat,ats triumph,sector 104,1.75,7642.0,2290.0,Super Built up area 2290(212.75 sq.m.)Carpet a...,3,4,3+,12.0,North-West,Relatively New,2290.0,NaN,1800.00,1,1,0,1,1,1,21,763.333333
4,flat,breez global heights,sohna road,0.46,6479.0,710.0,Carpet area: 710 (65.96 sq.m.),2,2,2,6.0,East,Relatively New,NaN,NaN,710.00,0,0,0,0,0,2,49,355.000000

In [6]:
train_df = df.drop(columns=['society','price_per_sqft'])

In [7]:
train_df.head()

,property_type,sector,price,area,areaWithType,bedRoom,bathroom,balcony,floorNum,facing,agePossession,super_built_up_area,built_up_area,carpet_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score,area_room_ratio
0,flat,sector 79,1.10,864.0,Super Built up area 1490(138.43 sq.m.)Carpet a...,3,3,3,22.0,South-West,Relatively New,1490.0,NaN,863.91,1,0,0,1,0,0,135,288.000000
1,flat,sector 103,1.50,1730.0,Super Built up area 1730(160.72 sq.m.)Carpet a...,3,3,3+,6.0,NaN,Under Construction,1730.0,NaN,1725.00,0,0,0,0,0,0,58,576.666667
2,flat,sector 71,0.95,1198.0,Super Built up area 1198(111.3 sq.m.),2,2,2,5.0,South,Moderately Old,1198.0,NaN,NaN,0,0,0,0,0,1,142,599.000000
3,flat,sector 104,1.75,2290.0,Super Built up area 2290(212.75 sq.m.)Carpet a...,3,4,3+,12.0,North-West,Relatively New,2290.0,NaN,1800.00,1,1,0,1,1,1,21,763.333333
4,flat,sohna road,0.46,710.0,Carpet area: 710 (65.96 sq.m.),2,2,2,6.0,East,Relatively New,NaN,NaN,710.00,0,0,0,0,0,2,49,355.000000

In [11]:
sns.heatmap(train_df.corr())

ValueError: could not convert string to float: 'flat'

In [12]:
train_df.corr()['price'].sort_values(ascending=False)

ValueError: could not convert string to float: 'flat'

In [ ]:
# cols in question

# numerical -> luxury_score, others, floorNum
# categorical -> property_type, sector, agePossession